Tf academic calendar 24 : 필터 및 월별 필터 컴포넌트 제작
uoslife/uoslife-client pull request #508
Opened 2024-05-31 16:24 UTC by yeonnybus

# Key Changes

- 내 일정에서의 필터 버튼, 모든 일정에서의 월별 필터 컴포넌트 UI 제작

# Details

- FilterButton : 내 일정에서의 버튼 하나 컴포넌트
- FilterButtonGroup : 필요한 버튼 모은 컴포넌트
- MontlyFilter : 월별 필터(이제 보니 monthly 오타났음...)

# To Reviewers

- 지적 부탁드립니다.

# Closes Issue

close #ISSUE

2024-06-02 08:30 UTC, choidongjune reviewed
+ src/features/uos_lifestyle/academic_calendar/components/FilterButtonGroup.tsx

setSelectedButtonId 토글로 구현해야 될 것 같네요

2024-06-03 14:27 UTC, alicehrk reviewed
작업하느라 수고 정말 많으셨습니다!! 😄

2024-06-03 14:57 UTC, alicehrk requested changes

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/assets/images/arrow_back_ios.png
이건 진짜 단순 궁금증인데 ios가 붙는 이유가 뭔가요..?

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/AcademicCalendarScreen.tsx
> +
JS를 이용하면 현재 날짜를 조회할 수 있습니다! 
(ex) `const currentDate = new Date();` 
현재 날짜를 기준으로, default 값을 설정하면 될 것 같습니다

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/MontlyFilter.tsx
수정해서 올릴 때 오타도 함께 수정해서 올려주세용

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/assets/images/arrow_back_ios.png
혹쉬 피그마 그대로 넣으신거라면,, 수정 부탁드립니다ㅎㅎㅎ

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +  selected: boolean; // 버튼이 선택되었는지 여부
코드로 이해할 수 있는 부분은 주석 처리 따로 안해주셔도 됩니당!

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +  } //그럴 상황 없겠지만, 혹시나 에러 방지
여기 주석도 생략해도 좋을 것 같습니다 :)

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +`;
Text의 경우 @uoslife/design-system에서 제공하는 `Txt`로 작업해야 합니다!
사용 예시 ⬇️
```
<Txt
    label="올해의 도서관 이용 내역"
    color="grey190"
    typograph="titleLarge"
/>
 ```

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +  padding-right: 9px;
이 친구들 한번에 묶어도 좋을 것 같슴니당

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +  background-color: #fff;
색상의 경우도 Txt처럼 colors라는 상수를 지정해서 사용하고 있습니다! colors를 이용한 코드로 수정해주세요 :D

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/FilterButtonGroup.tsx
> +  };
여기 주석도 마찬가지입니다!

2024-06-03 14:57 UTC, alicehrk commented on src/features/uos_lifestyle/academic_calendar/components/MontlyFilter.tsx
> +`;
여기 Text도 Txt를 사용한걸로 바꿔주세요!

2024-06-04 10:50 UTC, alicehrk requested changes

2024-06-04 10:53 UTC, choidongjune commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +      {text ? <ButtonText>{text}</ButtonText> : null}
클린 코드까지 섭렵하신... 역시 팀장님..

2024-06-04 11:37 UTC, yeonnybus commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +      {text ? <ButtonText>{text}</ButtonText> : null}
첨에 이렇게 썼었는데 에러나서 고쳤는데
왜 갑자기 되지???
하람효과 ㄷㄷ

2024-06-04 11:49 UTC, closed without merging