[feature/tf-academic-calendar-24] 필터 및 월별 필터 컴포넌트 제작
uoslife/uoslife-client pull request #517
Opened 2024-06-04 11:54 UTC by yeonnybus

# Key Changes

- 필터 버튼 컴포넌트, 월간 필터 컴포넌트 제작
- 요구사항 수정

# Details

- 쓸모없는 주석 삭제
- 디자인시스템(TxT,colors) 적용
- 클린코드
- arrow 이미지 파일명 수정
- montlyFilter.tsx -> monthlyFilter.tsx 파일명 수정
- Date 추가 및 월 이동 동작 함수 추가(주석처리)
- 브랜치 변경

# To Reviewers

- 감사합니당당당근

# Closes Issue

close #ISSUE

2024-06-04 14:57 UTC, eunbae0 requested changes

2024-06-04 14:57 UTC, eunbae0 commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +      {imageSource && <ButtonImage source={imageSource} />}
design-system의 `<Icon />`컴포넌트에 filter 항목도 추가해뒀으니, 패키지를 업데이트 한 후 적용시켜주시면 감사하겠습니다.

```bash
$ yarn add @uoslife/design-system
```

2024-06-04 14:57 UTC, eunbae0 commented on src/features/uos_lifestyle/academic_calendar/components/MonthlyFilter.tsx
> +      </ArrowButton>
마찬가지로 새로운 이미지 assets를 추가할 필요 없이, design-system의 Icon 컴포넌트를 이용하시면 됩니다.

2024-06-04 14:57 UTC, eunbae0 commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +const ButtonContainer = styled.TouchableOpacity<{isSelected: boolean}>`
기본적으로 버튼을 누르는 동작에서는 RN에서는 Pressable이 권장됩니다.
애니메이션이 필요하다면 `<AnimatePress />` 컴포넌트를 이용하여 통일성을 맞춰주시면 감사하겠습니다.

2024-06-04 14:59 UTC, eunbae0 commented
추가적으로 PR에는 누가 작업했는지 알기 위해 Assignees에 본인을 달아주시면 감사하겠습니다.

2024-06-05 05:11 UTC, yeonnybus commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +      {imageSource && <ButtonImage source={imageSource} />}
감사합니다
해당 아이콘으로 수정하겠습니다

2024-06-05 05:11 UTC, yeonnybus commented on src/features/uos_lifestyle/academic_calendar/components/MonthlyFilter.tsx
> +      </ArrowButton>
호출할 수 있는 design-system의 Icon의 전체 목록을 볼 수 있는 방법이 있을까요?

2024-06-05 05:12 UTC, yeonnybus commented on src/features/uos_lifestyle/academic_calendar/components/FilterButton.tsx
> +const ButtonContainer = styled.TouchableOpacity<{isSelected: boolean}>`
감사합니다  고려해서 수정하겠습니당

2024-06-27 12:38 UTC, closed without merging